name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  cancel-previoius-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  build-all:
    runs-on: ubuntu-4-16
    steps:
      - name: check out
        uses: actions/checkout@v4

      - name: main build
        uses: ./.github/actions/gradle-task
        with:
          task: jar compileKotlin
          write-cache-key: main-build-artifacts

  spotless:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: spotless
        uses: ./.github/actions/gradle-task-with-commit
        with:
          personal-access-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fix-task: spotlessApply
          check-task: spotlessCheck

  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ktlint
        uses: ./.github/actions/gradle-task-with-commit
        with:
          personal-access-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fix-task: ktlintFormat
          check-task: ktlintCheck

  dependency-guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: dependency-guard
        uses: ./.github/actions/gradle-task-with-commit
        with:
          personal-access-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fix-task: dependencyGuardBaseline
          check-task: dependencyGuard

  moduleCheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: moduleCheck
        uses: ./.github/actions/gradle-task-with-commit
        with:
          personal-access-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fix-task: moduleCheckAuto
          check-task: moduleCheck

  artifacts-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: artifacts-check
        uses: ./.github/actions/gradle-task-with-commit
        with:
          personal-access-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fix-task: artifactsDump
          check-task: artifactsCheck

  check-version-is-snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: check version is snapshot
        uses: ./.github/actions/gradle-task
        with:
          task: checkVersionIsSnapshot

  detekt:
    runs-on: ubuntu-4-16
    steps:
      - uses: actions/checkout@v4
      - name: detektAll
        uses: ./.github/actions/gradle-task
        with:
          task: detektAll
          restore-cache-key: main-build-artifacts

      - name: merge detekt SARIF reports
        run: ./gradlew detektReportMerge

      - name: Upload SARIF to Github using the upload-sarif action
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: build/reports/detekt/merged.sarif

  unit-tests-ubuntu:
    runs-on: ubuntu-4-16
    steps:
      - name: check out
        uses: actions/checkout@v4
      - name: unit tests
        uses: ./.github/actions/gradle-task
        with:
          task: test
          restore-cache-key: main-build-artifacts

      - name: Archive test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-results-ubuntu
          path: ${{ github.workspace }}/**/build/reports/tests/

      - name: Unit test results
        uses: mikepenz/action-junit-report@v4
        if: failure()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: "**/build/**/TEST-*.xml"
          check_name: Unit Test Results - ubuntu

  integration-tests-ubuntu:
    runs-on: ubuntu-4-16
    steps:
      - name: check out
        uses: actions/checkout@v4
      - name: integration tests
        uses: ./.github/actions/gradle-task
        with:
          task: integrationTest
          restore-cache-key: main-build-artifacts

      - name: Archive test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-results-ubuntu
          path: ${{ github.workspace }}/**/build/reports/tests/

      - name: Integration test results
        uses: mikepenz/action-junit-report@v4
        if: failure()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: "**/build/**/TEST-*.xml"
          check_name: Integration Test Results - ubuntu

  unit-tests-windows:
    runs-on: windows-8-32
    steps:
      - name: check out
        uses: actions/checkout@v4
      - name: unit tests
        uses: ./.github/actions/gradle-task
        with:
          task: test
          restore-cache-key: main-build-artifacts

      - name: Archive test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-results-windows
          path: ${{ github.workspace }}/**/build/reports/tests/

      - name: unit test results
        uses: mikepenz/action-junit-report@v4
        if: failure()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: "**/build/**/TEST-*.xml"
          check_name: Unit Test Results - windows

  integration-tests-windows:
    runs-on: windows-8-32
    steps:
      - name: check out
        uses: actions/checkout@v4
      - name: integration tests
        uses: ./.github/actions/gradle-task
        with:
          task: integrationTest
          restore-cache-key: main-build-artifacts

      - name: Archive test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-results-windows
          path: ${{ github.workspace }}/**/build/reports/tests/

      - name: Integration test results
        uses: mikepenz/action-junit-report@v4
        if: failure()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: "**/build/**/TEST-*.xml"
          check_name: Integration Test Results - windows

  all-green:
    if: always()
    runs-on: ubuntu-latest
    needs:
      - artifacts-check
      - check-version-is-snapshot
      - dependency-guard
      - detekt
      - integration-tests-ubuntu
      - integration-tests-windows
      - ktlint
      - moduleCheck
      - spotless
      - unit-tests-ubuntu
      - unit-tests-windows

    steps:
      - name: require that all other jobs have passed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
