name: CI
run-name: ${{ github.workflow }} on '${{ github.event.pull_request.title }}'

on:
  pull_request:
  workflow_dispatch:

jobs:
  cancel-previoius-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@85880fa0301c86cca9da44039ee3bb12d3bedbfa # 0.12.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-all:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: main build
        uses: rickbusarow/actions/gradle-task@bf0940965387f10bcb8b6699a79499d18167dfbe # v1
        with:
          task: jar compileKotlin
          write-cache-key: main-build-artifacts

  spotless:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@31c86eb3b33c9b601a1f60f98dcbfd1d70f379b4 # v1
        id: app-token
        with:
          app-id: ${{ secrets.PR_BOT_APP_ID }}
          private-key: ${{ secrets.PR_BOT_PRIVATE_KEY }}

      - name: spotless
        uses: rickbusarow/actions/gradle-task-with-commit@bf0940965387f10bcb8b6699a79499d18167dfbe # v1
        with:
          personal-access-token: ${{ steps.app-token.outputs.token }}
          fix-task: spotlessApply
          check-task: spotlessCheck

  ktlint:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@31c86eb3b33c9b601a1f60f98dcbfd1d70f379b4 # v1
        id: app-token
        with:
          app-id: ${{ secrets.PR_BOT_APP_ID }}
          private-key: ${{ secrets.PR_BOT_PRIVATE_KEY }}

      - name: ktlint
        uses: rickbusarow/actions/gradle-task-with-commit@bf0940965387f10bcb8b6699a79499d18167dfbe # v1
        with:
          personal-access-token: ${{ steps.app-token.outputs.token }}
          fix-task: ktlintFormat
          check-task: ktlintCheck

  dependency-guard:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@31c86eb3b33c9b601a1f60f98dcbfd1d70f379b4 # v1
        id: app-token
        with:
          app-id: ${{ secrets.PR_BOT_APP_ID }}
          private-key: ${{ secrets.PR_BOT_PRIVATE_KEY }}

      - name: dependency-guard
        uses: rickbusarow/actions/gradle-task-with-commit@bf0940965387f10bcb8b6699a79499d18167dfbe # v1
        with:
          personal-access-token: ${{ steps.app-token.outputs.token }}
          fix-task: dependencyGuardBaseline
          check-task: dependencyGuard

  moduleCheck:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@31c86eb3b33c9b601a1f60f98dcbfd1d70f379b4 # v1
        id: app-token
        with:
          app-id: ${{ secrets.PR_BOT_APP_ID }}
          private-key: ${{ secrets.PR_BOT_PRIVATE_KEY }}

      - name: moduleCheck
        uses: rickbusarow/actions/gradle-task-with-commit@bf0940965387f10bcb8b6699a79499d18167dfbe # v1
        with:
          personal-access-token: ${{ steps.app-token.outputs.token }}
          fix-task: moduleCheckAuto
          check-task: moduleCheck

  artifacts-check:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@31c86eb3b33c9b601a1f60f98dcbfd1d70f379b4 # v1
        id: app-token
        with:
          app-id: ${{ secrets.PR_BOT_APP_ID }}
          private-key: ${{ secrets.PR_BOT_PRIVATE_KEY }}

      - name: artifacts-check
        uses: rickbusarow/actions/gradle-task-with-commit@bf0940965387f10bcb8b6699a79499d18167dfbe # v1
        with:
          personal-access-token: ${{ steps.app-token.outputs.token }}
          fix-task: artifactsDump
          check-task: artifactsCheck

  check-version-is-snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: check version is snapshot
        uses: rickbusarow/actions/gradle-task@bf0940965387f10bcb8b6699a79499d18167dfbe # v1
        with:
          task: checkVersionIsSnapshot

  detekt:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: detektAll
        uses: rickbusarow/actions/gradle-task@bf0940965387f10bcb8b6699a79499d18167dfbe # v1
        with:
          task: detektAll
          restore-cache-key: main-build-artifacts

      - name: merge detekt SARIF reports
        run: ./gradlew detektReportMerge

      - name: Upload SARIF to Github using the upload-sarif action
        uses: github/codeql-action/upload-sarif@4fa2a7953630fd2f3fb380f21be14ede0169dd4f # v3
        if: success() || failure()
        with:
          sarif_file: build/reports/detekt/merged.sarif

  unit-tests-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: unit tests
        uses: rickbusarow/actions/gradle-task@bf0940965387f10bcb8b6699a79499d18167dfbe # v1
        with:
          task: test
          restore-cache-key: main-build-artifacts

      - name: Archive test results
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4
        if: failure()
        with:
          name: test-results-ubuntu
          path: ${{ github.workspace }}/**/build/reports/tests/

      - name: Unit test results
        uses: mikepenz/action-junit-report@db71d41eb79864e25ab0337e395c352e84523afe # v4
        if: failure()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: "**/build/**/TEST-*.xml"
          check_name: Unit Test Results - ubuntu

  integration-tests-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: integration tests
        uses: rickbusarow/actions/gradle-task@bf0940965387f10bcb8b6699a79499d18167dfbe # v1
        with:
          task: integrationTest
          restore-cache-key: main-build-artifacts

      - name: Archive test results
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4
        if: failure()
        with:
          name: test-results-ubuntu
          path: ${{ github.workspace }}/**/build/reports/tests/

      - name: Integration test results
        uses: mikepenz/action-junit-report@db71d41eb79864e25ab0337e395c352e84523afe # v4
        if: failure()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: "**/build/**/TEST-*.xml"
          check_name: Integration Test Results - ubuntu

  unit-tests-windows:
    runs-on: windows-latest
    steps:
      - name: check out
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: unit tests
        uses: rickbusarow/actions/gradle-task@bf0940965387f10bcb8b6699a79499d18167dfbe # v1
        with:
          task: test
          restore-cache-key: main-build-artifacts

      - name: Archive test results
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4
        if: failure()
        with:
          name: test-results-windows
          path: ${{ github.workspace }}/**/build/reports/tests/

      - name: unit test results
        uses: mikepenz/action-junit-report@db71d41eb79864e25ab0337e395c352e84523afe # v4
        if: failure()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: "**/build/**/TEST-*.xml"
          check_name: Unit Test Results - windows

  integration-tests-windows:
    runs-on: windows-latest
    steps:
      - name: check out
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: integration tests
        uses: rickbusarow/actions/gradle-task@bf0940965387f10bcb8b6699a79499d18167dfbe # v1
        with:
          task: integrationTest
          restore-cache-key: main-build-artifacts

      - name: Archive test results
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4
        if: failure()
        with:
          name: test-results-windows
          path: ${{ github.workspace }}/**/build/reports/tests/

      - name: Integration test results
        uses: mikepenz/action-junit-report@db71d41eb79864e25ab0337e395c352e84523afe # v4
        if: failure()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: "**/build/**/TEST-*.xml"
          check_name: Integration Test Results - windows

  all-checks:
    if: always()
    runs-on: ubuntu-latest
    needs:
      - artifacts-check
      - check-version-is-snapshot
      - dependency-guard
      - detekt
      - integration-tests-ubuntu
      - integration-tests-windows
      - ktlint
      - moduleCheck
      - spotless
      - unit-tests-ubuntu
      - unit-tests-windows

    steps:
      - name: require that all other jobs have passed
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
