name: Label Pull Request
run-name: ${{ github.workflow }} on '${{ github.event.pull_request.title }}'

on:
  # `pull_request_target` makes it so that the action is run against the configuration in the
  # destination branch, instead of the one in the PR branch.
  - pull_request_target

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
      # Pull requests currently don't include labels with their 'write' permission, so add issues
      # https://github.com/googleapis/release-please-action/issues/1105#issuecomment-2780292262
      issues: write
    runs-on: ubuntu-latest

    steps:
      # see https://github.com/actions/labeler
      - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5
        with:
          configuration-path: ".github/labeler-config.yml"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          # automatically remove labels if the PR changed and made them invalid
          sync-labels: true
