name: Publish snapshot
run-name: ${{ github.workflow }} on ${{ github.event.pull_request.title }}

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  build-all:
    runs-on: macos-latest
    steps:
      - name: check out
        uses: actions/checkout@v4

      - name: main build
        uses: rickbusarow/actions/gradle-task@v1
        with:
          task: jar compileKotlin
          write-cache-key: main-build-artifacts

      - name: Publish Snapshots
        uses: rickbusarow/actions/gradle-task@v1
        with:
          task: publish
          write-cache-key: local-m2
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
